from PyQt6 import QtCore, QtGui, QtWidgets
from pathlib import Path
from subprocess import Popen
from music_tag import load_file
from unicodedata import normalize
from youtubesearchpython import SearchVideos
from yt_dlp import YoutubeDL
from re import sub
from sys import argv, exit


class Ui_EchoSyncProject(object):
    def setupUi(self, EchoSyncProject):
        EchoSyncProject.setObjectName('EchoSyncProject')
        EchoSyncProject.resize(600, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EchoSyncProject.sizePolicy().hasHeightForWidth())
        EchoSyncProject.setSizePolicy(sizePolicy)
        EchoSyncProject.setMinimumSize(QtCore.QSize(600, 410))
        EchoSyncProject.setMaximumSize(QtCore.QSize(600, 410))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        EchoSyncProject.setFont(font)
        EchoSyncProject.setMouseTracking(True)
        EchoSyncProject.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        EchoSyncProject.setAcceptDrops(False)
        EchoSyncProject.setWindowTitle('EchoSync Project')
        EchoSyncProject.setToolTip(str())
        EchoSyncProject.setToolTipDuration(0)
        EchoSyncProject.setStatusTip(str())
        EchoSyncProject.setWhatsThis(str())
        EchoSyncProject.setAccessibleName(str())
        EchoSyncProject.setAccessibleDescription(str())
        EchoSyncProject.setStyleSheet('background-color: #1e1f22;')
        EchoSyncProject.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        EchoSyncProject.setWindowFilePath(str())
        EchoSyncProject.setIconSize(QtCore.QSize(64, 64))
        self.urlListInputWindow = QtWidgets.QWidget(parent=EchoSyncProject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.urlListInputWindow.sizePolicy().hasHeightForWidth())
        self.urlListInputWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.urlListInputWindow.setFont(font)
        self.urlListInputWindow.setMouseTracking(True)
        self.urlListInputWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.urlListInputWindow.setAcceptDrops(False)
        self.urlListInputWindow.setToolTip(str())
        self.urlListInputWindow.setStatusTip(str())
        self.urlListInputWindow.setWhatsThis(str())
        self.urlListInputWindow.setAccessibleName(str())
        self.urlListInputWindow.setAccessibleDescription(str())
        self.urlListInputWindow.setStyleSheet('background-color: #1e1f22;')
        self.urlListInputWindow.setObjectName('urlListInputWindow')
        self.background0 = QtWidgets.QLabel(parent=self.urlListInputWindow)
        self.background0.setGeometry(QtCore.QRect(-1, 0, 600, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background0.sizePolicy().hasHeightForWidth())
        self.background0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.background0.setFont(font)
        self.background0.setMouseTracking(True)
        self.background0.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.background0.setAcceptDrops(True)
        self.background0.setToolTip(str())
        self.background0.setStatusTip(str())
        self.background0.setWhatsThis(str())
        self.background0.setAccessibleName(str())
        self.background0.setAccessibleDescription(str())
        self.background0.setStyleSheet('background-color: #1e1f22;')
        self.background0.setText(str())
        self.background0.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.background0.setObjectName('background0')
        self.applicationName = QtWidgets.QLabel(parent=self.urlListInputWindow)
        self.applicationName.setGeometry(QtCore.QRect(0, 20, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applicationName.sizePolicy().hasHeightForWidth())
        self.applicationName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Sitka Small')
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.applicationName.setFont(font)
        self.applicationName.setMouseTracking(True)
        self.applicationName.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.applicationName.setAcceptDrops(False)
        self.applicationName.setToolTip(str())
        self.applicationName.setStatusTip(str())
        self.applicationName.setWhatsThis(str())
        self.applicationName.setAccessibleName(str())
        self.applicationName.setAccessibleDescription(str())
        self.applicationName.setStyleSheet('font: bold 16pt \'Sitka Small\'; color: #ffffff;')
        self.applicationName.setText('EchoSync Project')
        self.applicationName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.applicationName.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.applicationName.setObjectName('applicationName')
        self.inputUrlList = QtWidgets.QTextEdit(parent=self.urlListInputWindow)
        self.inputUrlList.setGeometry(QtCore.QRect(60, 120, 480, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputUrlList.sizePolicy().hasHeightForWidth())
        self.inputUrlList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Cascadia Code')
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.inputUrlList.setFont(font)
        self.inputUrlList.setMouseTracking(True)
        self.inputUrlList.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.inputUrlList.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.inputUrlList.setToolTip(str())
        self.inputUrlList.setStatusTip(str())
        self.inputUrlList.setWhatsThis(str())
        self.inputUrlList.setAccessibleName(str())
        self.inputUrlList.setAccessibleDescription(str())
        self.inputUrlList.setStyleSheet('font: 8pt \'Cascadia Code\'; color: #ffffff; background-color: rgba(255, 255, 255, 100); border-style: outset; border-width: 0px; border-radius: 6px;')
        self.inputUrlList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputUrlList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputUrlList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.inputUrlList.setDocumentTitle(str())
        self.inputUrlList.setUndoRedoEnabled(True)
        self.inputUrlList.setHtml('<!DOCTYPE HTML PUBLIC \'-//W3C//DTD HTML 4.0//EN\' \'http://www.w3.org/TR/REC-html40/strict.dtd\'>\n'
'<html><head><meta name=\'qrichtext\' content=\'1\' /><style type=\'text/css\'>\n'
'p, li { white-space: pre-wrap; }\n'
'</style></head><body style=\' font-family:\'Cascadia Code\'; font-size:8pt; font-weight:400; font-style:normal;\'>\n'
'<p style=\'-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\'><br /></p></body></html>')
        self.inputUrlList.setAcceptRichText(False)
        self.inputUrlList.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.inputUrlList.setPlaceholderText('https://www.example.com/music?id=0123456789')
        self.inputUrlList.setObjectName('inputUrlList')
        self.msgAskForUrls = QtWidgets.QLabel(parent=self.urlListInputWindow)
        self.msgAskForUrls.setGeometry(QtCore.QRect(0, 70, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgAskForUrls.sizePolicy().hasHeightForWidth())
        self.msgAskForUrls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Medium')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.msgAskForUrls.setFont(font)
        self.msgAskForUrls.setMouseTracking(True)
        self.msgAskForUrls.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgAskForUrls.setAcceptDrops(False)
        self.msgAskForUrls.setToolTip(str())
        self.msgAskForUrls.setStatusTip(str())
        self.msgAskForUrls.setWhatsThis(str())
        self.msgAskForUrls.setAccessibleName(str())
        self.msgAskForUrls.setAccessibleDescription(str())
        self.msgAskForUrls.setStyleSheet('font: 10pt \'Quicksand Medium\';')
        self.msgAskForUrls.setText('<html><head/><body><p align=\'center\'><span style=\' font-size:10pt; color:#ffffff;\'>Enter the URLs of the songs you want to download (one url per line)</span></p></body></html>')
        self.msgAskForUrls.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgAskForUrls.setObjectName('msgAskForUrls')
        self.btnNext = QtWidgets.QPushButton(parent=self.urlListInputWindow)
        self.btnNext.setGeometry(QtCore.QRect(218, 340, 160, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Medium')
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btnNext.setFont(font)
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNext.setMouseTracking(True)
        self.btnNext.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btnNext.setToolTip(str())
        self.btnNext.setStatusTip(str())
        self.btnNext.setWhatsThis(str())
        self.btnNext.setAccessibleName(str())
        self.btnNext.setAccessibleDescription(str())
        self.btnNext.setStyleSheet('QPushButton {font: bold 10pt \'Quicksand Medium\'; color: rgb(255, 255, 255); background-color: rgba(4, 201, 149, 200); border-color: rgba(4, 201, 149, 200); border-style: outset; border-width: 1px; border-radius: 5px;} QPushButton:hover {font: bold 10pt \'Quicksand Medium\'; color: rgb(255, 255, 255); background-color: rgba(4, 201, 149, 200); border-color: rgba(4, 201, 149, 200); border-style: inset; border-width: 1px; border-radius: 5px;}')
        self.btnNext.setText('DOWNLOAD')
        self.btnNext.setShortcut(str())
        self.btnNext.setObjectName('btnNext')
        self.downloadProgress = QtWidgets.QWidget(parent=self.urlListInputWindow)
        self.downloadProgress.setGeometry(QtCore.QRect(0, -1, 580, 540))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadProgress.sizePolicy().hasHeightForWidth())
        self.downloadProgress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.downloadProgress.setFont(font)
        self.downloadProgress.setMouseTracking(True)
        self.downloadProgress.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.downloadProgress.setToolTip(str())
        self.downloadProgress.setStatusTip(str())
        self.downloadProgress.setWhatsThis(str())
        self.downloadProgress.setAccessibleName(str())
        self.downloadProgress.setAccessibleDescription(str())
        self.downloadProgress.setStyleSheet('background-color: #1e1f22;')
        self.downloadProgress.setObjectName('downloadProgress')
        self.background1 = QtWidgets.QLabel(parent=self.downloadProgress)
        self.background1.setGeometry(QtCore.QRect(0, 0, 600, 410))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background1.sizePolicy().hasHeightForWidth())
        self.background1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.background1.setFont(font)
        self.background1.setMouseTracking(True)
        self.background1.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.background1.setAcceptDrops(True)
        self.background1.setToolTip(str())
        self.background1.setStatusTip(str())
        self.background1.setWhatsThis(str())
        self.background1.setAccessibleName(str())
        self.background1.setAccessibleDescription(str())
        self.background1.setStyleSheet('background-color: #1e1f22;')
        self.background1.setText(str())
        self.background1.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.background1.setObjectName('background1')
        self.taskProgressTitle = QtWidgets.QLabel(parent=self.downloadProgress)
        self.taskProgressTitle.setGeometry(QtCore.QRect(0, 20, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskProgressTitle.sizePolicy().hasHeightForWidth())
        self.taskProgressTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Sitka Small')
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.taskProgressTitle.setFont(font)
        self.taskProgressTitle.setMouseTracking(True)
        self.taskProgressTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.taskProgressTitle.setAcceptDrops(False)
        self.taskProgressTitle.setToolTip(str())
        self.taskProgressTitle.setStatusTip(str())
        self.taskProgressTitle.setWhatsThis(str())
        self.taskProgressTitle.setAccessibleName(str())
        self.taskProgressTitle.setAccessibleDescription(str())
        self.taskProgressTitle.setStyleSheet('font: bold 14pt \'Sitka Small\'; color: #ffffff;')
        self.taskProgressTitle.setText('Task progress')
        self.taskProgressTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.taskProgressTitle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.taskProgressTitle.setObjectName('taskProgressTitle')
        self.msgSearchingURLsByTitle = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgSearchingURLsByTitle.setGeometry(QtCore.QRect(50, 140, 150, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgSearchingURLsByTitle.sizePolicy().hasHeightForWidth())
        self.msgSearchingURLsByTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.msgSearchingURLsByTitle.setFont(font)
        self.msgSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgSearchingURLsByTitle.setMouseTracking(True)
        self.msgSearchingURLsByTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgSearchingURLsByTitle.setAcceptDrops(False)
        self.msgSearchingURLsByTitle.setToolTip(str())
        self.msgSearchingURLsByTitle.setStatusTip(str())
        self.msgSearchingURLsByTitle.setWhatsThis(str())
        self.msgSearchingURLsByTitle.setAccessibleName(str())
        self.msgSearchingURLsByTitle.setAccessibleDescription(str())
        self.msgSearchingURLsByTitle.setStyleSheet('font: 10pt \'Quicksand Mediuml\'; color: #ffffff;')
        self.msgSearchingURLsByTitle.setText('Searching songs by title:')
        self.msgSearchingURLsByTitle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgSearchingURLsByTitle.setObjectName('msgSearchingURLsByTitle')
        self.msgSortingLinksStrings = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgSortingLinksStrings.setGeometry(QtCore.QRect(50, 100, 130, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgSortingLinksStrings.sizePolicy().hasHeightForWidth())
        self.msgSortingLinksStrings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.msgSortingLinksStrings.setFont(font)
        self.msgSortingLinksStrings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgSortingLinksStrings.setMouseTracking(True)
        self.msgSortingLinksStrings.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgSortingLinksStrings.setAcceptDrops(False)
        self.msgSortingLinksStrings.setToolTip(str())
        self.msgSortingLinksStrings.setStatusTip(str())
        self.msgSortingLinksStrings.setWhatsThis(str())
        self.msgSortingLinksStrings.setAccessibleName(str())
        self.msgSortingLinksStrings.setAccessibleDescription(str())
        self.msgSortingLinksStrings.setStyleSheet('font: 10pt \'Quicksand Mediuml\'; color: #ffffff;')
        self.msgSortingLinksStrings.setText('Sorting links/strings:')
        self.msgSortingLinksStrings.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgSortingLinksStrings.setObjectName('msgSortingLinksStrings')
        self.pbSortingLinks = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbSortingLinks.setGeometry(QtCore.QRect(220, 110, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSortingLinks.sizePolicy().hasHeightForWidth())
        self.pbSortingLinks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbSortingLinks.setFont(font)
        self.pbSortingLinks.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbSortingLinks.setMouseTracking(True)
        self.pbSortingLinks.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbSortingLinks.setToolTip(str())
        self.pbSortingLinks.setStatusTip(str())
        self.pbSortingLinks.setWhatsThis(str())
        self.pbSortingLinks.setAccessibleName(str())
        self.pbSortingLinks.setAccessibleDescription(str())
        self.pbSortingLinks.setStyleSheet('font:9pt \'Quicksand Mediuml\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbSortingLinks.setProperty('value', 0)
        self.pbSortingLinks.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbSortingLinks.setFormat('%p%')
        self.pbSortingLinks.setObjectName('pbSortingLinks')
        self.pbSearchingURLsByTitle = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbSearchingURLsByTitle.setGeometry(QtCore.QRect(220, 150, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSearchingURLsByTitle.sizePolicy().hasHeightForWidth())
        self.pbSearchingURLsByTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.pbSearchingURLsByTitle.setFont(font)
        self.pbSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbSearchingURLsByTitle.setMouseTracking(True)
        self.pbSearchingURLsByTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbSearchingURLsByTitle.setToolTip(str())
        self.pbSearchingURLsByTitle.setStatusTip(str())
        self.pbSearchingURLsByTitle.setWhatsThis(str())
        self.pbSearchingURLsByTitle.setAccessibleName(str())
        self.pbSearchingURLsByTitle.setAccessibleDescription(str())
        self.pbSearchingURLsByTitle.setStyleSheet('font:9pt \'Quicksand Mediuml\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbSearchingURLsByTitle.setProperty('value', 0)
        self.pbSearchingURLsByTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbSearchingURLsByTitle.setInvertedAppearance(False)
        self.pbSearchingURLsByTitle.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.pbSearchingURLsByTitle.setFormat('%p%')
        self.pbSearchingURLsByTitle.setObjectName('pbSearchingURLsByTitle')
        self.pbDownloadingSongsByUrl = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbDownloadingSongsByUrl.setGeometry(QtCore.QRect(220, 190, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDownloadingSongsByUrl.sizePolicy().hasHeightForWidth())
        self.pbDownloadingSongsByUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.pbDownloadingSongsByUrl.setFont(font)
        self.pbDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbDownloadingSongsByUrl.setMouseTracking(True)
        self.pbDownloadingSongsByUrl.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbDownloadingSongsByUrl.setToolTip(str())
        self.pbDownloadingSongsByUrl.setStatusTip(str())
        self.pbDownloadingSongsByUrl.setWhatsThis(str())
        self.pbDownloadingSongsByUrl.setAccessibleName(str())
        self.pbDownloadingSongsByUrl.setAccessibleDescription(str())
        self.pbDownloadingSongsByUrl.setStyleSheet('font:9pt \'Quicksand Mediuml\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbDownloadingSongsByUrl.setProperty('value', 0)
        self.pbDownloadingSongsByUrl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbDownloadingSongsByUrl.setInvertedAppearance(False)
        self.pbDownloadingSongsByUrl.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.pbDownloadingSongsByUrl.setFormat('%p%')
        self.pbDownloadingSongsByUrl.setObjectName('pbDownloadingSongsByUrl')
        self.msgDownloadingSongsByUrl = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgDownloadingSongsByUrl.setGeometry(QtCore.QRect(50, 180, 160, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgDownloadingSongsByUrl.sizePolicy().hasHeightForWidth())
        self.msgDownloadingSongsByUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Mediuml')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.msgDownloadingSongsByUrl.setFont(font)
        self.msgDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgDownloadingSongsByUrl.setMouseTracking(True)
        self.msgDownloadingSongsByUrl.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgDownloadingSongsByUrl.setAcceptDrops(False)
        self.msgDownloadingSongsByUrl.setToolTip(str())
        self.msgDownloadingSongsByUrl.setStatusTip(str())
        self.msgDownloadingSongsByUrl.setWhatsThis(str())
        self.msgDownloadingSongsByUrl.setAccessibleName(str())
        self.msgDownloadingSongsByUrl.setAccessibleDescription(str())
        self.msgDownloadingSongsByUrl.setStyleSheet('font: 10pt \'Quicksand Mediuml\'; color: #ffffff;')
        self.msgDownloadingSongsByUrl.setText('Downloading songs by url:')
        self.msgDownloadingSongsByUrl.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgDownloadingSongsByUrl.setObjectName('msgDownloadingSongsByUrl')
        self.btnImportFromFile = QtWidgets.QPushButton(parent=self.urlListInputWindow)
        self.btnImportFromFile.setGeometry(QtCore.QRect(500, 260, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportFromFile.sizePolicy().hasHeightForWidth())
        self.btnImportFromFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Medium')
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btnImportFromFile.setFont(font)
        self.btnImportFromFile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnImportFromFile.setMouseTracking(True)
        self.btnImportFromFile.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btnImportFromFile.setToolTip(str())
        self.btnImportFromFile.setStatusTip(str())
        self.btnImportFromFile.setWhatsThis(str())
        self.btnImportFromFile.setAccessibleName(str())
        self.btnImportFromFile.setAccessibleDescription(str())
        self.btnImportFromFile.setStyleSheet('background-color: rgba(68, 68, 69, 200); border-color: rgba(68, 68, 69, 200); border-style: outset; border-width: 1px; border-radius: 5px;')
        self.btnImportFromFile.setText(str())
        self.btnImportFromFile.setShortcut(str())
        self.btnImportFromFile.setObjectName('btnImportFromFile')
        self.downloadProgress.raise_()
        self.background0.raise_()
        self.applicationName.raise_()
        self.inputUrlList.raise_()
        self.msgAskForUrls.raise_()
        self.btnNext.raise_()
        self.btnImportFromFile.raise_()
        EchoSyncProject.setCentralWidget(self.urlListInputWindow)

        self.main(EchoSyncProject)
        QtCore.QMetaObject.connectSlotsByName(EchoSyncProject)

    def main(self, mainWindow) -> None:
        mainWindow.setFixedSize(600, 410)

        def go_to_progress() -> None:
            self.downloadProgress.show()
            self.downloadProgress.raise_()

            self.pbSortingLinks.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
            query_dict = sort_links(self.inputUrlList.toPlainText().split('\n'))
            self.pbSortingLinks.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))

            self.pbSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
            url_query_list = search_songs_by_title(query_dict)
            self.pbSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))

            mainWindow.setFixedSize(600, 255)
            self.pbDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
            download_song(url_query_list)
            self.inputUrlList.clear()
            self.inputUrlList.setFocus()
            self.pbDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
            mainWindow.setFixedSize(600, 410)

            self.downloadProgress.hide()
            self.urlListInputWindow.show()
            self.urlListInputWindow.raise_()

        def import_queries_from_file() -> None:
            def set_ui_input_list(queries: list) -> None:
                existing_queries = set(query.strip() for query in self.inputUrlList.toPlainText().split('\n'))
                queries = '\n'.join(filter(None, set(existing_queries.union(map(str.strip, queries)))))
                self.inputUrlList.setText(queries)

            input_file_path = Path(QtWidgets.QFileDialog.getOpenFileName(mainWindow, 'Select a text file with the URLs/Queries', str(), 'Text and CSV files (*.txt *.csv)')[0]).absolute()

            if input_file_path.is_file():
                with open(input_file_path, 'r', encoding='utf-8') as fi:
                    if input_file_path.suffix == '.txt':
                        queries = fi.readlines()
                    elif input_file_path.suffix == '.csv':
                        queries = fi.read().split(',')

                queries = [query.strip() for query in queries]
                set_ui_input_list(queries)

        self.btnImportFromFile.clicked.connect(import_queries_from_file)
        self.btnNext.clicked.connect(go_to_progress)

        def sort_links(query_list: list) -> dict:
            query_dict = {'links': list(), 'titles': list()}

            self.pbSortingLinks.setValue(0)
            for query in query_list:
                self.pbSortingLinks.setValue(int((query_list.index(query) + 1) / len(query_list) * 100))
                if query.startswith('http'):
                    query_dict['links'].append(query)
                else:
                    query_dict['titles'].append(query)

            self.pbSortingLinks.setValue(100)

            return query_dict

        def search_songs_by_title(query_dict: dict) -> list:
            url_query_list = list()

            self.pbSearchingURLsByTitle.setValue(0)

            for query in query_dict['titles']:
                query_url = str(SearchVideos(query, offset=1, mode='dict', max_results=1).result()['search_result'][0]['link'])
                url_query_list.append(query_url)
                self.pbSearchingURLsByTitle.setValue(int((query_dict['titles'].index(query) + 1) / len(query_dict['titles']) * 100))

            self.pbSearchingURLsByTitle.setValue(100)

            url_query_list.extend(query_dict['links'])
            return url_query_list

        def download_song(url_query_list: list) -> None:
            self.pbDownloadingSongsByUrl.setValue(0)

            Path(Path.cwd(), 'songs').mkdir(parents=True, exist_ok=True)

            def fix_title(title: str) -> str:
                normalized_title = normalize('NFKD', title).encode('ASCII', 'ignore').decode('utf-8')
                sanitized_title = sub(r'\s+', ' ', sub(r'[^a-zA-Z0-9\-_()[\]{}# ]', str(), normalized_title).strip())

                return sanitized_title

            ydl_opts_info = {
                'quiet': True,
                'no_warnings': True,
            }

            for url in url_query_list:
                song_info = YoutubeDL(ydl_opts_info).extract_info(url, download=False)
                output_file_path_wo_ext = Path(Path.cwd(), 'songs', fix_title(song_info['title']))
                temp_output_file_path_wo_ext = Path(f'{output_file_path_wo_ext}-temp')

                ydl_opts_download = {
                    'format': 'bestaudio/best',
                    'outtmpl': f'{temp_output_file_path_wo_ext}.mp3',
                    'quiet': True,
                    'no_warnings': True,
                    'nooverwrites': True,
                }

                with YoutubeDL(ydl_opts_download) as ydl:
                    ydl.download([url])

                temp_output_file_path = Path(f'{temp_output_file_path_wo_ext}.mp3').absolute()
                output_file_path = Path(f'{output_file_path_wo_ext}.opus').absolute()

                ffmpeg_proc = Popen(f'"ffmpeg.exe" -i "{temp_output_file_path}" -c:a libopus -b:a 192k -y -hide_banner -loglevel quiet "{output_file_path}"', shell=True)
                ffmpeg_proc.wait()

                temp_output_file_path.unlink(missing_ok=True)

                f = load_file(output_file_path)
                f['tracktitle'] = fix_title(song_info['title'])
                f['artist'] = song_info['uploader']
                f['year'] = song_info['upload_date'][:4]
                f.save()

                self.pbDownloadingSongsByUrl.setValue(int((url_query_list.index(url) + 1) / len(url_query_list) * 100))

            self.pbDownloadingSongsByUrl.setValue(100)


if __name__ == '__main__':
    app = QtWidgets.QApplication(argv)
    EchoSyncProject = QtWidgets.QMainWindow()
    EchoSyncProject.setWindowIcon(QtGui.QIcon('icon.ico'))
    ui = Ui_EchoSyncProject()
    ui.setupUi(EchoSyncProject)
    EchoSyncProject.show()
    exit(app.exec())
