from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_echosync_project(object):
    def setupUi(self, echosync_project):
        echosync_project.setObjectName('echosync_project')
        echosync_project.resize(600, 410)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(echosync_project.sizePolicy().hasHeightForWidth())
        echosync_project.setSizePolicy(sizePolicy)
        echosync_project.setMinimumSize(QtCore.QSize(600, 410))
        echosync_project.setMaximumSize(QtCore.QSize(600, 410))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        echosync_project.setFont(font)
        echosync_project.setMouseTracking(True)
        echosync_project.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        echosync_project.setAcceptDrops(False)
        echosync_project.setWindowTitle('EchoSync Project')
        echosync_project.setToolTip(str())
        echosync_project.setToolTipDuration(0)
        echosync_project.setStatusTip(str())
        echosync_project.setWhatsThis(str())
        echosync_project.setAccessibleName(str())
        echosync_project.setAccessibleDescription(str())
        echosync_project.setStyleSheet('background-color: #1e1f22;')
        echosync_project.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        echosync_project.setWindowFilePath(str())
        echosync_project.setIconSize(QtCore.QSize(64, 64))
        self.mainStartMenu = QtWidgets.QWidget(parent=echosync_project)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainStartMenu.sizePolicy().hasHeightForWidth())
        self.mainStartMenu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.mainStartMenu.setFont(font)
        self.mainStartMenu.setMouseTracking(True)
        self.mainStartMenu.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.mainStartMenu.setAcceptDrops(False)
        self.mainStartMenu.setToolTip(str())
        self.mainStartMenu.setStatusTip(str())
        self.mainStartMenu.setWhatsThis(str())
        self.mainStartMenu.setAccessibleName(str())
        self.mainStartMenu.setAccessibleDescription(str())
        self.mainStartMenu.setStyleSheet('background-color: #1e1f22;')
        self.mainStartMenu.setObjectName('mainStartMenu')
        self.background0 = QtWidgets.QLabel(parent=self.mainStartMenu)
        self.background0.setGeometry(QtCore.QRect(-1, 0, 600, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background0.sizePolicy().hasHeightForWidth())
        self.background0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.background0.setFont(font)
        self.background0.setMouseTracking(True)
        self.background0.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.background0.setAcceptDrops(True)
        self.background0.setToolTip(str())
        self.background0.setStatusTip(str())
        self.background0.setWhatsThis(str())
        self.background0.setAccessibleName(str())
        self.background0.setAccessibleDescription(str())
        self.background0.setStyleSheet('background-color: #1e1f22;')
        self.background0.setText(str())
        self.background0.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.background0.setObjectName('background0')
        self.applicationName = QtWidgets.QLabel(parent=self.mainStartMenu)
        self.applicationName.setGeometry(QtCore.QRect(0, 30, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applicationName.sizePolicy().hasHeightForWidth())
        self.applicationName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.applicationName.setFont(font)
        self.applicationName.setMouseTracking(True)
        self.applicationName.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.applicationName.setAcceptDrops(False)
        self.applicationName.setToolTip(str())
        self.applicationName.setStatusTip(str())
        self.applicationName.setWhatsThis(str())
        self.applicationName.setAccessibleName(str())
        self.applicationName.setAccessibleDescription(str())
        self.applicationName.setStyleSheet('font: bold 16pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.applicationName.setText('EchoSync Project')
        self.applicationName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.applicationName.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.applicationName.setObjectName('applicationName')
        self.inputUrlList = QtWidgets.QTextEdit(parent=self.mainStartMenu)
        self.inputUrlList.setGeometry(QtCore.QRect(60, 120, 480, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputUrlList.sizePolicy().hasHeightForWidth())
        self.inputUrlList.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputUrlList.setFont(font)
        self.inputUrlList.setMouseTracking(True)
        self.inputUrlList.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.inputUrlList.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.inputUrlList.setToolTip(str())
        self.inputUrlList.setStatusTip(str())
        self.inputUrlList.setWhatsThis(str())
        self.inputUrlList.setAccessibleName(str())
        self.inputUrlList.setAccessibleDescription(str())
        self.inputUrlList.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; color: #ffffff; background-color: rgba(255, 255, 255, 60); border-style: outset; border-width: 0px; border-radius: 6px;')
        self.inputUrlList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputUrlList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inputUrlList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.inputUrlList.setDocumentTitle(str())
        self.inputUrlList.setUndoRedoEnabled(True)
        self.inputUrlList.setHtml('<!DOCTYPE HTML PUBLIC \'-//W3C//DTD HTML 4.0//EN\' \'http://www.w3.org/TR/REC-html40/strict.dtd\'>\n'
'<html><head><meta name=\'qrichtext\' content=\'1\' /><style type=\'text/css\'>\n'
'p, li { white-space: pre-wrap; }\n'
'</style></head><body style=\' font-family:\'Microsoft JhengHei UIl\'; font-size:10pt; font-weight:400; font-style:normal;\'>\n'
'<p style=\'-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Cascadia Code\'; font-size:8pt;\'><br /></p></body></html>')
        self.inputUrlList.setAcceptRichText(False)
        self.inputUrlList.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.inputUrlList.setPlaceholderText('Type the urls or queries you want to download into this text field...')
        self.inputUrlList.setObjectName('inputUrlList')
        self.msgAskForUrls = QtWidgets.QLabel(parent=self.mainStartMenu)
        self.msgAskForUrls.setGeometry(QtCore.QRect(0, 70, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgAskForUrls.sizePolicy().hasHeightForWidth())
        self.msgAskForUrls.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.msgAskForUrls.setFont(font)
        self.msgAskForUrls.setMouseTracking(True)
        self.msgAskForUrls.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgAskForUrls.setAcceptDrops(False)
        self.msgAskForUrls.setToolTip(str())
        self.msgAskForUrls.setStatusTip(str())
        self.msgAskForUrls.setWhatsThis(str())
        self.msgAskForUrls.setAccessibleName(str())
        self.msgAskForUrls.setAccessibleDescription(str())
        self.msgAskForUrls.setStyleSheet('font: 16pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.msgAskForUrls.setText('<html><head/><body><p align=\'center\'><span style=\' font-size:10pt; color:#ffffff;\'>Enter the URLs of the songs you want to download (one url per line)</span></p></body></html>')
        self.msgAskForUrls.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgAskForUrls.setObjectName('msgAskForUrls')
        self.btnNext = QtWidgets.QPushButton(parent=self.mainStartMenu)
        self.btnNext.setGeometry(QtCore.QRect(218, 340, 160, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext.sizePolicy().hasHeightForWidth())
        self.btnNext.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnNext.setFont(font)
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnNext.setMouseTracking(True)
        self.btnNext.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btnNext.setToolTip(str())
        self.btnNext.setStatusTip(str())
        self.btnNext.setWhatsThis(str())
        self.btnNext.setAccessibleName(str())
        self.btnNext.setAccessibleDescription(str())
        self.btnNext.setStyleSheet('QPushButton {font: bold 10pt \'Microsoft JhengHei UIl\'; color: rgb(255, 255, 255); background-color: rgba(4, 201, 149, 200); border-color: rgba(4, 201, 149, 200); border-style: outset; border-width: 1px; border-radius: 5px;} QPushButton:hover {font: bold 10pt \'Microsoft JhengHei UIl\'; color: rgb(255, 255, 255); background-color: rgba(4, 201, 149, 200); border-color: rgba(4, 201, 149, 200); border-style: inset; border-width: 1px; border-radius: 5px;}')
        self.btnNext.setText('DOWNLOAD')
        self.btnNext.setShortcut(str())
        self.btnNext.setObjectName('btnNext')
        self.downloadProgress = QtWidgets.QWidget(parent=self.mainStartMenu)
        self.downloadProgress.setGeometry(QtCore.QRect(0, -1, 580, 540))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadProgress.sizePolicy().hasHeightForWidth())
        self.downloadProgress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.downloadProgress.setFont(font)
        self.downloadProgress.setMouseTracking(True)
        self.downloadProgress.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.downloadProgress.setToolTip(str())
        self.downloadProgress.setStatusTip(str())
        self.downloadProgress.setWhatsThis(str())
        self.downloadProgress.setAccessibleName(str())
        self.downloadProgress.setAccessibleDescription(str())
        self.downloadProgress.setStyleSheet('background-color: #1e1f22;')
        self.downloadProgress.setObjectName('downloadProgress')
        self.background1 = QtWidgets.QLabel(parent=self.downloadProgress)
        self.background1.setGeometry(QtCore.QRect(0, 0, 600, 410))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.background1.sizePolicy().hasHeightForWidth())
        self.background1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.background1.setFont(font)
        self.background1.setMouseTracking(True)
        self.background1.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.background1.setAcceptDrops(True)
        self.background1.setToolTip(str())
        self.background1.setStatusTip(str())
        self.background1.setWhatsThis(str())
        self.background1.setAccessibleName(str())
        self.background1.setAccessibleDescription(str())
        self.background1.setStyleSheet('background-color: #1e1f22;')
        self.background1.setText(str())
        self.background1.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.background1.setObjectName('background1')
        self.taskProgressTitle = QtWidgets.QLabel(parent=self.downloadProgress)
        self.taskProgressTitle.setGeometry(QtCore.QRect(0, 30, 600, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.taskProgressTitle.sizePolicy().hasHeightForWidth())
        self.taskProgressTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.taskProgressTitle.setFont(font)
        self.taskProgressTitle.setMouseTracking(True)
        self.taskProgressTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.taskProgressTitle.setAcceptDrops(False)
        self.taskProgressTitle.setToolTip(str())
        self.taskProgressTitle.setStatusTip(str())
        self.taskProgressTitle.setWhatsThis(str())
        self.taskProgressTitle.setAccessibleName(str())
        self.taskProgressTitle.setAccessibleDescription(str())
        self.taskProgressTitle.setStyleSheet('font: bold 16pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.taskProgressTitle.setText('Task progress')
        self.taskProgressTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.taskProgressTitle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.taskProgressTitle.setObjectName('taskProgressTitle')
        self.msgSearchingURLsByTitle = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgSearchingURLsByTitle.setGeometry(QtCore.QRect(50, 140, 161, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgSearchingURLsByTitle.sizePolicy().hasHeightForWidth())
        self.msgSearchingURLsByTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.msgSearchingURLsByTitle.setFont(font)
        self.msgSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgSearchingURLsByTitle.setMouseTracking(True)
        self.msgSearchingURLsByTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgSearchingURLsByTitle.setAcceptDrops(False)
        self.msgSearchingURLsByTitle.setToolTip(str())
        self.msgSearchingURLsByTitle.setStatusTip(str())
        self.msgSearchingURLsByTitle.setWhatsThis(str())
        self.msgSearchingURLsByTitle.setAccessibleName(str())
        self.msgSearchingURLsByTitle.setAccessibleDescription(str())
        self.msgSearchingURLsByTitle.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.msgSearchingURLsByTitle.setText('Searching songs by title:')
        self.msgSearchingURLsByTitle.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgSearchingURLsByTitle.setObjectName('msgSearchingURLsByTitle')
        self.msgSortingLinksStrings = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgSortingLinksStrings.setGeometry(QtCore.QRect(50, 100, 161, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgSortingLinksStrings.sizePolicy().hasHeightForWidth())
        self.msgSortingLinksStrings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.msgSortingLinksStrings.setFont(font)
        self.msgSortingLinksStrings.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgSortingLinksStrings.setMouseTracking(True)
        self.msgSortingLinksStrings.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgSortingLinksStrings.setAcceptDrops(False)
        self.msgSortingLinksStrings.setToolTip(str())
        self.msgSortingLinksStrings.setStatusTip(str())
        self.msgSortingLinksStrings.setWhatsThis(str())
        self.msgSortingLinksStrings.setAccessibleName(str())
        self.msgSortingLinksStrings.setAccessibleDescription(str())
        self.msgSortingLinksStrings.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.msgSortingLinksStrings.setText('Sorting links/strings:')
        self.msgSortingLinksStrings.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgSortingLinksStrings.setObjectName('msgSortingLinksStrings')
        self.pbSortingLinks = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbSortingLinks.setGeometry(QtCore.QRect(220, 110, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSortingLinks.sizePolicy().hasHeightForWidth())
        self.pbSortingLinks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbSortingLinks.setFont(font)
        self.pbSortingLinks.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbSortingLinks.setMouseTracking(True)
        self.pbSortingLinks.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbSortingLinks.setToolTip(str())
        self.pbSortingLinks.setStatusTip(str())
        self.pbSortingLinks.setWhatsThis(str())
        self.pbSortingLinks.setAccessibleName(str())
        self.pbSortingLinks.setAccessibleDescription(str())
        self.pbSortingLinks.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbSortingLinks.setProperty('value', 0)
        self.pbSortingLinks.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbSortingLinks.setFormat('%p%')
        self.pbSortingLinks.setObjectName('pbSortingLinks')
        self.pbSearchingURLsByTitle = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbSearchingURLsByTitle.setGeometry(QtCore.QRect(220, 150, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSearchingURLsByTitle.sizePolicy().hasHeightForWidth())
        self.pbSearchingURLsByTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbSearchingURLsByTitle.setFont(font)
        self.pbSearchingURLsByTitle.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbSearchingURLsByTitle.setMouseTracking(True)
        self.pbSearchingURLsByTitle.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbSearchingURLsByTitle.setToolTip(str())
        self.pbSearchingURLsByTitle.setStatusTip(str())
        self.pbSearchingURLsByTitle.setWhatsThis(str())
        self.pbSearchingURLsByTitle.setAccessibleName(str())
        self.pbSearchingURLsByTitle.setAccessibleDescription(str())
        self.pbSearchingURLsByTitle.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbSearchingURLsByTitle.setProperty('value', 0)
        self.pbSearchingURLsByTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbSearchingURLsByTitle.setInvertedAppearance(False)
        self.pbSearchingURLsByTitle.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.pbSearchingURLsByTitle.setFormat('%p%')
        self.pbSearchingURLsByTitle.setObjectName('pbSearchingURLsByTitle')
        self.pbDownloadingSongsByUrl = QtWidgets.QProgressBar(parent=self.downloadProgress)
        self.pbDownloadingSongsByUrl.setGeometry(QtCore.QRect(220, 190, 330, 14))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbDownloadingSongsByUrl.sizePolicy().hasHeightForWidth())
        self.pbDownloadingSongsByUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbDownloadingSongsByUrl.setFont(font)
        self.pbDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.WaitCursor))
        self.pbDownloadingSongsByUrl.setMouseTracking(True)
        self.pbDownloadingSongsByUrl.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.pbDownloadingSongsByUrl.setToolTip(str())
        self.pbDownloadingSongsByUrl.setStatusTip(str())
        self.pbDownloadingSongsByUrl.setWhatsThis(str())
        self.pbDownloadingSongsByUrl.setAccessibleName(str())
        self.pbDownloadingSongsByUrl.setAccessibleDescription(str())
        self.pbDownloadingSongsByUrl.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; background-color: rgba(255, 255, 255, 200); border-color: rgba(0, 0, 0, 0); border-style: outset; border-width: 1px; border-radius: 4px;')
        self.pbDownloadingSongsByUrl.setProperty('value', 0)
        self.pbDownloadingSongsByUrl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pbDownloadingSongsByUrl.setInvertedAppearance(False)
        self.pbDownloadingSongsByUrl.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.pbDownloadingSongsByUrl.setFormat('%p%')
        self.pbDownloadingSongsByUrl.setObjectName('pbDownloadingSongsByUrl')
        self.msgDownloadingSongsByUrl = QtWidgets.QLabel(parent=self.downloadProgress)
        self.msgDownloadingSongsByUrl.setGeometry(QtCore.QRect(50, 180, 160, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgDownloadingSongsByUrl.sizePolicy().hasHeightForWidth())
        self.msgDownloadingSongsByUrl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Microsoft JhengHei UIl')
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.msgDownloadingSongsByUrl.setFont(font)
        self.msgDownloadingSongsByUrl.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.msgDownloadingSongsByUrl.setMouseTracking(True)
        self.msgDownloadingSongsByUrl.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.msgDownloadingSongsByUrl.setAcceptDrops(False)
        self.msgDownloadingSongsByUrl.setToolTip(str())
        self.msgDownloadingSongsByUrl.setStatusTip(str())
        self.msgDownloadingSongsByUrl.setWhatsThis(str())
        self.msgDownloadingSongsByUrl.setAccessibleName(str())
        self.msgDownloadingSongsByUrl.setAccessibleDescription(str())
        self.msgDownloadingSongsByUrl.setStyleSheet('font: 10pt \'Microsoft JhengHei UIl\'; color: #ffffff;')
        self.msgDownloadingSongsByUrl.setText('Downloading songs by url:')
        self.msgDownloadingSongsByUrl.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.msgDownloadingSongsByUrl.setObjectName('msgDownloadingSongsByUrl')
        self.btnImportFromFile = QtWidgets.QPushButton(parent=self.mainStartMenu)
        self.btnImportFromFile.setGeometry(QtCore.QRect(500, 260, 31, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImportFromFile.sizePolicy().hasHeightForWidth())
        self.btnImportFromFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily('Quicksand Medium')
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.btnImportFromFile.setFont(font)
        self.btnImportFromFile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnImportFromFile.setMouseTracking(True)
        self.btnImportFromFile.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.btnImportFromFile.setToolTip(str())
        self.btnImportFromFile.setStatusTip(str())
        self.btnImportFromFile.setWhatsThis(str())
        self.btnImportFromFile.setAccessibleName(str())
        self.btnImportFromFile.setAccessibleDescription(str())
        self.btnImportFromFile.setStyleSheet('background-color: #00000000;')
        self.btnImportFromFile.setText(str())
        self.btnImportFromFile.setShortcut(str())
        self.btnImportFromFile.setObjectName('btnImportFromFile')
        self.downloadProgress.raise_()
        self.background0.raise_()
        self.applicationName.raise_()
        self.inputUrlList.raise_()
        self.msgAskForUrls.raise_()
        self.btnNext.raise_()
        self.btnImportFromFile.raise_()
        echosync_project.setCentralWidget(self.mainStartMenu)

        QtCore.QMetaObject.connectSlotsByName(echosync_project)
